language: android
jdk: openjdk8
android:
  components:
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - android-sdk-license-.+
  - google-gdk-license-.+
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_ad4d1427361f_key -iv $encrypted_ad4d1427361f_iv
  -in travis-ci.keystore.enc -out travis-ci.keystore -d
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e\n8933bad161af4178b1185d1a37fbf41ea5269c55"
  > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- touch ./pushlibrary.gradle
- touch ./pushlibrary-debug.gradle
- touch ./pushlibrary-release.gradle
script: "./gradlew clean build"
